theme: jeckll-theme-minimal
title: Xin Chen's homepage
description: My personal profile

url: https://cx-333.github.io

# can not modify
lsi: false
safe: true
inremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
